### ISSUE TITLE
Support for RNNs

### ISSUE THREAD

**Issue by dhyeyjani** [NVlabs/timeloop#102]
Does it support RNN architectures?

**Comment by vmiheer** [comment]
Hi @dhyeyjani, can you please post the exact computation in terms of loop code?
E.g. https://github.com/NVlabs/timeloop/issues/67#issuecomment-850765080

**Comment by dhyeyjani** [comment]
I haven't actually coded up the loop nest yet... just wanted to know if it is possible to run [recurrent layers](http://d2l.ai/chapter_recurrent-neural-networks/rnn.html) like the convolutional layers.

**Comment by vmiheer** [comment]
Most dense loop codes should be re-presentable in timeloop.

**Comment by nelliewu-nv** [comment]
For each evaluation run, Timeloop analyzes the performance of running a single layer on the specified architecture, and does not consider inter-layers performance. So with Timeloop, a network needs to be modeled as a sequence of layers with no recurrent connections.
