### ISSUE TITLE
Memory access count for psum is missing?

### ISSUE THREAD

**Issue by LY-Mei** [NVlabs/timeloop#103]
Hi,

While evaluating AlexNet on the Eyeriss-like architecture provided by "eyeriss_like-int16.yaml", we noticed something strange in the output access count and hope you can clarify this for us.

The issue we found is in "alexnet_2.stats.txt" for any output memory level. Take the global buffer level (shared_glb) for example:
        Scalar reads (per-instance)              : 3980288
        Scalar updates (per-instance)          : 4153344
        Scalar fills (per-instance)                  : 2076672
        Energy (per-scalar-access)               : 18.80 pJ
        Energy (total)                           : 191992003.84 pJ

Energy (total) = (Scalar reads + Scalar updates + Scalar fills) * Energy (per-scalar-access), in which, as we understood,
Scalar reads are the # of times the memory is read from, to serve the level below;
Scalar updates are the # of times the memory is written by the level below;
Scalar fills are the # of times the memory talks to the level above; (as shown in the figure below)
![image](https://user-images.githubusercontent.com/55059827/126665704-bc2ef22c-6472-4f54-945d-9dee639faff7.png)

We noticed that the memory access count from DRAM to global buffer for output is missing. The same holds true for other output memory levels. Is there something we overlooked or should these missing access counts be present? 

The related files are attached. Thank you!
[alexnet_2.map.txt](https://github.com/NVlabs/timeloop/files/6863486/alexnet_2.map.txt)
[alexnet_2.stats.txt](https://github.com/NVlabs/timeloop/files/6863487/alexnet_2.stats.txt)

Best regards,
Linyan

**Comment by poant** [comment]
Hi Linyan,

Thanks for reporting this. We will take a look at this issue and see if there is any miscalculation.

**Comment by angshuman-parashar** [comment]
Stale issue, closing.
