### ISSUE TITLE
 A possible input memory access count error?

### ISSUE THREAD

**Issue by LY-Mei** [NVlabs/timeloop#104]
Hi,

We found a possible input memory access count error in the following experiment (files attached, same experiment as the previous issue I just opened).
[alexnet_2.map.txt](https://github.com/NVlabs/timeloop/files/6863748/alexnet_2.map.txt)
[alexnet_2.stats.txt](https://github.com/NVlabs/timeloop/files/6863749/alexnet_2.stats.txt)

The figure below illustrates our doubt.
![image](https://user-images.githubusercontent.com/55059827/126671806-39e4c61b-10ea-4e9f-83dd-99668770915f.png)
We don't know where the red "16" comes from? It's more correct to us if the ifmap_spad scaler fills per instance is 49920, which is the number of MAC operations per instance (1597440) divided by the input temporal data reuse factor at that level (32).

Just correct me if I overlooked something. Thank you in advance!

Best regards,
Linyan

**Comment by angshuman-parashar** [comment]
Stale issue, closing.
