### ISSUE TITLE
Cycle calculation in Timeloop

### ISSUE THREAD

**Issue by tanvisharma** [NVlabs/timeloop#108]
Does the cycle count in the output stats include the latency to bring the data to compute core (and latency hiding from higher memory levels) or is it only the total compute cycles count based on the number of MACCs? @nellie-wu

**Comment by tanvisharma** [comment]
Thank you for the quick response. 
Does this include all the levels in the memory or just the network connecting closest level (say Global buffer) to the PEs? Is it possible to write this in a mathematical formula?

(I skimmed through the code and could see Cycles() being calculated for the whole topology, considering each level (cycles = std::max(cycles, level->Cycles()). It takes into account the total number of accesses and the slowdown from bandwidth throttling as you mentioned. However, because of heavy hierarchy, the exact formula is getting difficult to understand)

**Comment by angshuman-parashar** [comment]
Yes it includes all levels in the hierarchy. Timeloop has no hard-coded notion of a "PE", an architecture is an arbitrary-depth tree of storage levels with arithmetic units at the leaves and networks running between levels.

As you correctly observed, the bandwidth consumption at each stage in the architecture is derived from the data-movement statistics. There's no easy formula to compute these statistics. There's a recursive analysis of the workload's loop nest in nest-analysis.cpp that takes into account the space-time behavior of all data tiles at every level, there's multicast analysis and peer-transfer analysis, bypassing of tensors at levels, and statistical sparsity analysis for compressed-sparse workloads. For some specific simple workloads/mappings with no bypassing and no compression and on a simple architecture without multicast/forwarding you may be able to come up with an algebraic expression that matches Timeloop's analysis results.
