### ISSUE TITLE
compute energy of mac operation problem

### ISSUE THREAD

**Issue by deepanshu761999** [NVlabs/timeloop#119]
"compute energy" of mac operation in timeloop-mapper.stats.txt file is not the same as in ERT_summary produced by Accelergy. It is always 1pJ in the timeloop-mapper.stats.txt.

**Comment by nellie-wu** [comment]
Have you compiled timeloop with the `-accelergy` flag? If correctly configured, you should see accelergy being executed in the terminal output when running timeloop.

If accelergy was executed, would you please provide your input files for us to try to reproduce the behavior?

**Comment by deepanshu761999** [comment]
Yes, I compiled timeloop with `--accelergy` flag. And I can see accelergy being executed.

I ran a couple of examples like Eyeriss_like and pim. Found out that energy per mac operation was different when compared to the example outputs provided with the examples itself. Then I tried changing the energy per mac operation and in the timeloop-model.ERT_summary.txt energy per mac is changing but in the timeloop-model.stats.txt compute energy is just 1pJ. However, I also tried changing energy per op of ADC and found that changes are consistent in both files. 

PS-I'm using Timeloopv2.0

**Comment by angshuman-parashar** [comment]
In order to help us reproduce the issue, could you please attach the exact yamls you are using for your run? You can concatenate everything into a single YAML.

**Comment by deepanshu761999** [comment]
[processing-in-memory-design.zip](https://github.com/NVlabs/timeloop/files/8053689/processing-in-memory-design.zip)

I have attached the zip file(it is an unchanged processing-in-memory example from accelergy project page). It also includes logs and stats.

Below is the ERT summary:

![ert_summary](https://user-images.githubusercontent.com/52217613/153716501-715c9623-b6e9-4537-86fe-6a207727f3f1.png)

while timeloop stats showing:

![timeloop_stats](https://user-images.githubusercontent.com/52217613/153716521-14e3e2c3-21b4-4267-9370-0c766afa1883.png)

**Comment by nellie-wu** [comment]
Thanks for providing the input files. We have updated the codebase to fix the issue, please pull and try again.

**Comment by Omar-Abdul-Aziz** [comment]
Hello,

I have the same problem with the SRAM memorry. 
https://github.com/NVlabs/timeloop/issues/202#issue-1633567799
 Could you support?
