### ISSUE TITLE
Tile size

### ISSUE THREAD

**Issue by nivi1501** [NVlabs/timeloop#122]
Hi,
How to estimate the tile size of an output feature map, weights, and ifmap using the mapper function? I wish to estimate the tile size generated in a single loop iteration (wrt DRAM). Suppose I get the following mapping from timeloop:
 {
      target = 0;
      type = "temporal";
      factors = "C1 K1 R11 S1 P1 Q1";
      permutation = "RCKSPQ";
    }, 
    {
      target = 1;
      type = "spatial";
      factors = "C1 K16 R1 S1 P1 Q11";
      permutation = "QKCRSP";
      split = 1;
    }, 
    {
      target = 1;
      type = "temporal";
      factors = "C1 K1 R1 S11 P1 Q1";
      permutation = "SCKRPQ";
    }, 
    {
      target = 2;
      type = "temporal";
      factors = "C3 K6 R1 S1 P55 Q5";
      permutation = "PQCKRS";
    }
Tile size for the output=55x5X6. I am not sure about this. Can anyone please help me out?

**Comment by nivi1501** [comment]
Thanks for the response, how can we compute delta size?

**Comment by angshuman-parashar** [comment]
In general it may change from iteration to iteration, and may also depend on the state of ancestor loops. You can reason about it manually by computing the tensor tiles corresponding to two specific consecutive iterations of any loop, and then calculating the set-difference between them. If you haven't done so already, we strongly recommend watching and working through one of our tutorials, that will help you build a strong intuitive foundation.

**Comment by nivi1501** [comment]
Thanks a lot :)
