### ISSUE TITLE
Inaccurate DRAM Access Count with Imperfect Factorization

### ISSUE THREAD

**Issue by hqjenny** [NVlabs/timeloop#153]
We observed a higher DRAM access count for both _Weights_ and _Inputs_ for Mapping 2 below when we move 2x `C` factors into the inner, which is counter-intuitive.

Given the two mappings below, take the DRAM access count of _Weights_ for example, it is computed as `122880x9x32=35389440` in mapping 1 and `245760x5x32=39321600` in mapping 2.  As a result, mapping 2 incurs more traffic than mapping 1. However, without the imperfect factor `C` in the mapping, they should be the same. 

**Mapping 1** (DRAM Weights Access is 35389440)
```
DRAM [ Weights:1081344 (1081344) Inputs:720896 (720896) Outputs:393216 (393216) ]
---------------------------------------------------------------------------------
| for P in [0:32)
|   for C in [0:9)
Scratchpad [ Weights:122880 (122880) Inputs:2560 (2560) ]
---------------------------------------------------------
|     for N in [0:1)
Accumulator [ Outputs:12288 (12288) ]
-------------------------------------
|       for P in [0:16)
|         for K in [0:48)
|           for C in [0:10,8)
|             for K in [0:16) (Spatial-Y)
|               for C in [0:16) (Spatial-X)
Registers [ Weights:1 (1) ]
---------------------------
|                 for N in [0:1)
```

**Mapping 2** (DRAM Weights Access is 39321600)
```DRAM [ Weights:1081344 (1081344) Inputs:720896 (720896) Outputs:393216 (393216) ]
---------------------------------------------------------------------------------
| for P in [0:32)
|   for C in [0:5)
Scratchpad [ Weights:245760 (245760) Inputs:5120 (5120) ]
---------------------------------------------------------
|     for N in [0:1)
Accumulator [ Outputs:12288 (12288) ]
-------------------------------------
|       for P in [0:16)
|         for K in [0:48)
|           for C in [0:20,8)
|             for K in [0:16) (Spatial-Y)
|               for C in [0:16) (Spatial-X)
Registers [ Weights:1 (1) ]
---------------------------
|                 for N in [0:1)
```

**Comment by angshuman-parashar** [comment]
Would it be possible to construct a simpler problem/arch that demonstrates this issue? That will help with both understanding the issue as well as debugging it later. I recommend progressively reducing problem dimensions (hopefully dropping many of them to 1) as long as you can see the discrepancy. And then simplify the architecture -- remove the scratchpad level, remove spatial fanouts etc.

**Comment by hqjennynv** [comment]
Added a fix PR https://github.com/NVlabs/timeloop/pull/154. 

Here is the logic flow chart for the imperfect factor mapping. 

[1-if](https://github.com/hqjennynv/timeloop/blob/02496b763aaabdc82c7ae418e30944a7380edbd5/src/loop-analysis/nest-analysis.cpp#L813), [2-if](https://github.com/hqjennynv/timeloop/blob/02496b763aaabdc82c7ae418e30944a7380edbd5/src/loop-analysis/nest-analysis.cpp#L832), [3-if](https://github.com/hqjennynv/timeloop/blob/02496b763aaabdc82c7ae418e30944a7380edbd5/src/loop-analysis/nest-analysis.cpp#L867), [4-if](https://github.com/hqjennynv/timeloop/blob/02496b763aaabdc82c7ae418e30944a7380edbd5/src/loop-analysis/nest-analysis.cpp#L892)

Iteration 0 and 1 are always executed (iteration index starts from 0).
 
1. if (num_iterations == 1)
 1-if: Delta -> iter0-0 
2. if (num_iterations == 2) 
 1-if: Delta -> iter0-0, set up iter0 cur 
 4-if: Delta -> iter1-iter0
3. If (num_iterations == 3)
 1-if: Delta -> iter0-0
 3-if: Delta -> iter1-iter0 use actual delta
 4-if: Delta -> iter2-iter1 
4. If (num_iterations == 4)
 1-if: Delta -> iter0-0
 2-if: Delta -> (iter1-iter0) x1, set up iter1 cur 
 3-if: Delta -> can use both iter2-iter1 or iter1-iter0, set up iter2 cur
 4-if:Delta -> iter3-iter2
5. If (num_iterations == N)
 1-if: Delta -> iter0-0
 2-if: Delta -> iter1-iter0 x 2, set up iter1 cur 
 3-if: Delta -> iter1-iter0 x1, set up iter(N-2) cur
 4-if: Delta -> iter(N-1)-iter(N-2)
