### ISSUE TITLE
Spatial split for the same problem dimension 

### ISSUE THREAD

**Issue by hqjenny** [NVlabs/timeloop#162]
Is it possible to perform a split of a single problem dimension in the spatial split specification?

According to the page: 
https://timeloop.csail.mit.edu/timeloop/input-formats/mapping
```  
split: 0 => RPK mapped to hardware-Y.
split: 1 => R mapped to hardware-X, PK mapped to hardware-Y.
split: 2 => RP mapped to hardware-X, K mapped to hardware-Y.
split: 3 => RPK mapped to hardware-X.
```

What if we have K=16 we would like to map it spatially to a mesh network of size meshX=4, meshY=4? Can we split along the K dimension, e.g. meshX= K4, meshY=K4? Currently, Timeloop will output an error saying K is exceeding the mesh-X size.

**Comment by angshuman-parashar** [comment]
The way to emulate this behavior is to create a new "logical" or "dummy" level. Assign meshX=K4 to the outer, and meshY=K4 to the inner. Set the size of the level to 0, and in the mapspace constraints set all tensors to bypass that level.

**Comment by hqjenny** [comment]
Okay. Thanks for the suggestions! I thought about this solution but was not sure if there is a better way to do this. 

In this case, for the mapper to explore all possible mappings, we should always create architectures with two memory levels, one with meshX=4 and the other dummy level with meshY=4, so the K=16 case can be explored. Is it correct?

**Comment by angshuman-parashar** [comment]
If you do not want an X*Y = 4*4 grid and instead lay out that level in a 16*1 (all-X) or 1*16 (all-Y) arrangement, then you do not need to create 2 logical levels.

**Comment by hqjenny** [comment]
Okay, I will use all X or all Y instead. Thanks for the suggestions, Angshu! 
If I understand correctly, XY=44 and all-X or all-Y will not incur any difference in latency performance but might incur a difference in energy since the hop counts might be different. Is it correct?

**Comment by angshuman-parashar** [comment]
That is correct.
