### ISSUE TITLE
Getting `undefined reference to ..` errors when building Timeloop with static libraries

### ISSUE THREAD

**Issue by hqjenny** [NVlabs/timeloop#165]
We found that when building Timeloop with `scons --static`, the following errors might show up from the linker complaining that 
```
undefined reference to `...`
```
or 
```
undefined reference to `vtable for ...`
```

The tool versions we used are: 
```
gcc-11.2.0
ld-2.27-28.base.el7_5.1
scons-2.3.0
```

**Comment by hqjenny** [comment]
A workaround to fix this error is to add the `mapperlib_sources` to all build dependencies of the binaries in the `src/SConscript` file: 

```
223c223
< metrics_sources = Split("""
---
> metrics_sources = mapperlib_sources + Split("""
228c228
< model_sources = Split("""
---
> model_sources = mapperlib_sources + Split("""
233c233
< mapper_sources = Split("""
---
> mapper_sources = mapperlib_sources + Split("""
239c239
< simple_mapper_sources = Split("""
---
> simple_mapper_sources = mapperlib_sources + Split("""
244c244
< design_space_sources = Split("""
---
> design_space_sources = mapperlib_sources + Split("""

```

**Comment by angshuman-parashar** [comment]
@gilbertmike @jsemer any thoughts? With static linking on some environments, it seems building the `libtimeloop` libraries first into `.a`s and then linking those into the final binaries causes the vtable errors, but directly linking the `.o`s into the final binaries does not cause the errors.

**Comment by hqjenny** [comment]
We found the errors are caused by scons picking up the wrong `ar` and `ranlib`  to create the static libraries. A fix is to add the following lines to SConstruct.
```
env.Replace(AR = "gcc-ar")
env.Replace(RANLIB = "gcc-ranlib")
``` 
changes are pushed to commit https://github.com/NVlabs/timeloop/commit/8e28dd93d2d43129ec5349a79d5a1950b6377c9d
