### ISSUE TITLE
Confused about the dummy buffer concept in timeloop

### ISSUE THREAD

**Issue by MustafaFayez** [NVlabs/timeloop#175]
From the tutorials, @angshuman-parashar showed dummy_buffers are helpful in spatial mapping of the same dimension in both X and Y directions.

What I am confused about is the meaning of temporal loops at the dummy buffer level.
In the eyeriss mapping example below:

`DRAM [ Weights:294912 Inputs:430592 Outputs:802816 ] 
----------------------------------------------------
| for Q in [0:4)
|   for M in [0:4)
|     for C in [0:8)

shared_glb [ Inputs:14848 Outputs:50176 ] 
-----------------------------------------
|       for M in [0:4)
|         for P in [0:56)
|           for Q in [0:14) (Spatial-X)

DummyBuffer [ ] 
---------------
|             for Q in [0:1)
|               for C in [0:4) (Spatial-Y)
|                 for S in [0:3) (Spatial-Y)

ifmap_spad [ Inputs:12 ] 
------------------------
|                   for Q in [0:1)

weights_spad [ Weights:192 ] 
----------------------------
|                     for R in [0:3)
|                       for C in [0:4)

psum_spad [ Outputs:16 ] 
------------------------
|                         for M in [0:16)
`
Can the dummy buffer have actual temporal loops (`for Q in [0:n)`) in the example? if so, where are these data stored in actual hardware? if not, how to prevent timeloop from producing such mappings?
Thank you.

**Comment by angshuman-parashar** [comment]
The `Q` loop has 1 iteration and does not really exist. It is being emitted because our mapping data structure nominally needs at least 1 loop at each level. In general when you create a dummy level, make sure to set all temporal bounds to 1 in the constraints.
