### ISSUE TITLE
Trouble instantiating multicast network

### ISSUE THREAD

**Issue by suyashbakshi** [NVlabs/timeloop#177]
I'm trying to instantiate the "SimpleMulticast" network for an example hardware architecture. But I keep getting the following error:
```
../timeloop-dev/timeloop/build/timeloop-model config/arch/arch.yaml config/prob/prob_3d_1.yaml config/map/mapping.yaml
execute:/home/myuser/.local/bin/accelergy config/arch/arch.yaml config/prob/prob_3d_1.yaml config/map/mapping.yaml --oprefix timeloop-model. -o ./ > timeloop-model.accelergy.log 2>&1
Failed to run Accelergy. Did you install Accelergy or specify ACCELERGYPATH correctly? Or check accelergy.log to see what went wrong
```

Attached is the arch.yaml used. 
[arch.yaml.txt](https://github.com/NVlabs/timeloop/files/10199400/arch.yaml.txt)
[mapping.yaml.txt](https://github.com/NVlabs/timeloop/files/10199402/mapping.yaml.txt)
[prob_3d_1.yaml.txt](https://github.com/NVlabs/timeloop/files/10199404/prob_3d_1.yaml.txt)

I do realize that in order to connect two different architecture components by using the network i will have to add "network_read"/"network_fill" etc. attributes to the components. But that will come later. Here, simply adding the network's definition into the arch.yaml is giving an error.

**Comment by suyashbakshi** [comment]
hello, I would really appreciate any help with this.
Thank you

**Comment by angshuman-parashar** [comment]
Is `accelergy.log` generated? If so could you paste its contents?

**Comment by suyashbakshi** [comment]
Yes, here it is. It also has outputs of few print statements that I added.

[timeloop-model.accelergy.log](https://github.com/NVlabs/timeloop/files/10270547/timeloop-model.accelergy.log)

**Comment by angshuman-parashar** [comment]
Thanks. The issue here is that the Accelergy plugins you are using do not recognize a `SimpleMulticast` network. @nellie-wu do we have such a plugin? If not, do you have a suggestion for @suyashbakshi in terms of how he can use/modify the `XYNoC` plugin to serve as a proxy energy estimator for the `SimpleMulticast` network?

**Comment by nellie-wu** [comment]
The `SimpleMulticast` network is not defined as a primitive component class in Accelergy, so there is no energy estimation support for this network class. To solve the problem, we need to define what this network looks like. For example, in a processing-in-memory design, a  `SimpleMulticast` network can be defined as a set of ADCs (with the `subclass` keyword), which then can be estimated: https://github.com/Accelergy-Project/processing-in-memory-design/blob/master/arch/system_PIM.yaml#L52  

For a regular digital design, the network can be simplified to wires, so I would suggest adding a compound component similar to the `XY_NoC` [here](https://github.com/Accelergy-Project/timeloop-accelergy-exercises/blob/master/workspace/exercises/2020.ispass/accelergy/04_eyeriss_like/input/components/XY_NoC.yaml ) and replace the `subclass` [here](https://github.com/Accelergy-Project/processing-in-memory-design/blob/master/arch/system_PIM.yaml#L52) to your compound component class name. This way, Accelergy will be able to use the wire length to estimate the cost of your network.

**Comment by suyashbakshi** [comment]
Thanks @angshuman-parashar @nellie-wu . I will try this out and get back. I do have a few questions:

- do I need any additional plugin apart from the ones I already have for estimating wire energy? Or does Accelergy have an inbuilt "wire" primitive component?
- Just to clarify, the "datawidth" attribute refers essentially to the operand datatype, correct? I.e., 8-bit, 16-bit etc., and not the width of the NoC. As we discussed earlier [here](https://github.com/NVlabs/timeloop/issues/136#issuecomment-1126727221) the NoC does not itself have a "width", and the bandwidth of data movement is determined by the individual components on either side of the NoC.
- This may not make sense, but is there a way to let Timeloop/accelergy to infer the minimum wire length required for connecting two individual components together based on their area? This would prevent the user from defining arbitrary wire lengths.

**Comment by suyashbakshi** [comment]
Thanks @nellie-wu I managed to get this working. I am still confused about how Timeloop estimates a rough floorplan and wire length, and would appreciate some more clarification.

Apart from that, a few specific questions:

1. does this XY_NoC represent a fan-out network similar to one in the example architecture below? Where the red boxes can be assumed as private register files of PEs and the fan-out happens between these PEs and a shared on-chip buffer.
![image](https://user-images.githubusercontent.com/16914056/212635840-3472e0f7-ae9b-4010-8d7c-209f594e6741.png)

2. Which distance specifically in this example architecture is defined by the attribute "Y_X_wire_avg_length" in "XY_NoC.yaml" ?
3. What is considered as a "hop" in this case? Is it the distance between any two PEs?

**Comment by suyashbakshi** [comment]
Hello, in addition to my previous questions, I have a few more follow-ups. I managed to add the [XY_NoC](https://github.com/Accelergy-Project/timeloop-accelergy-exercises/blob/master/workspace/exercises/2020.ispass/accelergy/04_eyeriss_like/input/components/XY_NoC.yaml) into my example architecture (arch.yaml attached below) to connect the GlobalBuffer and the RegisterFile components. I evaluated a mapping for a 3D convolution problem (mapping.yaml and prob_3d.yaml attached below) for this architecture using timeloop-model. 

However, the timeloop-model.stats.txt shows zero energy being accounted for all the 3 operands Weights, Inputs and Outputs. I would appreciate if you could help me find what I am missing to get the wire/NoC energy estimations.

My goal is to have a NoC, similar to the diagram shown in my previous post, between the GlobalBuffer and the RegisterFile and get energy estimations for data transfers between the both components.

[arch.txt](https://github.com/NVlabs/timeloop/files/10451897/arch.txt)
[mapping.txt](https://github.com/NVlabs/timeloop/files/10451901/mapping.txt)
[prob_3d_1.txt](https://github.com/NVlabs/timeloop/files/10451908/prob_3d_1.txt)
[timeloop-model.stats.txt](https://github.com/NVlabs/timeloop/files/10451911/timeloop-model.stats.txt)
[timeloop-model.flattened_architecture.txt](https://github.com/NVlabs/timeloop/files/10451916/timeloop-model.flattened_architecture.txt)
[timeloop-model.ERT_summary.txt](https://github.com/NVlabs/timeloop/files/10451918/timeloop-model.ERT_summary.txt)
[timeloop-model.ERT.txt](https://github.com/NVlabs/timeloop/files/10451923/timeloop-model.ERT.txt)

**Comment by suyashbakshi** [comment]
Hello, any suggestions for this?

**Comment by angshuman-parashar** [comment]
Apologies, none of us seem to have the cycles at this time to do any hands-on debugging. If you can look deeper into it and find out where the 0 energies are originating from, perhaps we can give you a pointer.

**Comment by suyashbakshi** [comment]
Thanks @angshuman-parashar . I will keep digging and try to find the issue. I just wondered if anyone have had previous experience dealing with wire energy issues. The troubling part is that the [eyeriss_like](workspace/exercises/2020.ispass/accelergy/04_eyeriss_like/input/components/XY_NoC.yaml) example that shows the usage of this XY_NoC also shows 0 energy for NoC even with all the plug-ins suggested installed.

What I found was that the Aladdin plug-in's ".py" wrapper script has conditionals that only provide wire energy estimations for 40nm and 45nm. I changed my architecture to use either of those, which resulted in the ERT being populated with energy data. Now, in the following line in [network-simple-multicast.cpp](https://github.com/NVlabs/timeloop/blob/f45704865085860a11699f6e8189c4276e4e541f/src/model/network-simple-multicast.cpp#L200) it is suggested to use "transfer" as the keyword for actions of NoC. However, the XY_NoC defines 2 actions "transfer_random" and "transfer_repeated", which don't seem to be parsed by the above mentioned line. I also changed one of the action's name to only "transfer" to check if that gets parsed as an action but it still did not.

I will keep looking but would appreciate any pointers.

**Comment by suyashbakshi** [comment]
Hello, I solved the above issue of getting zero energy for NoC. Following are my notes. I also have a few questions and would really appreciate some clarification on them.

Preface:
- the hardware architecture used here has 256 PEs, each with private register file. The multicast network connects the register files to the next higher level memory, the shared "Global buffer". And the final level in the architecture is a DRAM memory.

Notes:
1. The Aladdin plugin currently only supports 40nm and 45nm.
2. Aladdin plugin also only supports "transfer" and "transfer_random" actions as shown [here](https://github.com/Accelergy-Project/accelergy-aladdin-plug-in/blob/7fe410252d7aa515ed1d6dc8a29eaa2c4d5f3eaa/aladdin_table.py#L264). While the [XY_NoC](https://github.com/Accelergy-Project/timeloop-accelergy-exercises/blob/master/workspace/exercises/2020.ispass/accelergy/04_eyeriss_like/input/components/XY_NoC.yaml) has an action named "transfer_repeated" which does not seem to be supported. For me, I just changed it to "transfer" in XY_NoC.yaml.
3. [This](https://github.com/Accelergy-Project/processing-in-memory-design/blob/54d3e531dfaa1acc2f820fff0c43429d29011aa8/arch/system_PIM.yaml#L62) example demonstrating the usage of XY_NoC shows that the attribute "multicast_factor_argument" named as "num_destinations". However, Accelergy generates 2 attributes for the NoC in the generated ERT, namely, 1) n_cols_per_row and 2) n_rows. And when Timeloop parses the arch.yaml, it looks for "num_destinations" attribute in ERT [here](https://github.com/NVlabs/timeloop/blob/f45704865085860a11699f6e8189c4276e4e541f/src/model/network-simple-multicast.cpp#L209), but does not find any such attribute in the ERT. Simply changing the "multicast_factor_argument" to "n_cols_per_row" in the arch.yaml made Timeloop find the energy value in ERT for the corresponding "multicast factor" value for a given operand.

[arch.yaml.txt](https://github.com/NVlabs/timeloop/files/10540645/arch.yaml.txt)
[ERT.yaml.txt](https://github.com/NVlabs/timeloop/files/10540651/ERT.yaml.txt)
[XY_NoC.yaml.txt](https://github.com/NVlabs/timeloop/files/10540655/XY_NoC.yaml.txt)

Questions:
1. Between which components does the attribute "Y_X_wire_avg_length" in "XY_NoC.yaml" define an average length? Is it between the PEs and global buffer, or is it between 2 PEs themselves, or some other components?
2. What's considered a 'hop' for the given architecture?
3. How is the PE-to-PE data transfer latency determined?

**Comment by angshuman-parashar** [comment]
@nellie-wu would appreciate your feedback on Question 1.

Question 2 -- a hop is the distance between two neighboring nodes on the mesh in either X or Y direction.

Question 3 -- there's no latency modeling as of today. Bandwidth is modeled at storage interfaces, and the assumption is that the network is suitably provisioned so as to not bottleneck the available storage bandwidth. Or, put another way, the user should set the storage interface bandwidth as the minimum of network and storage interface bandwidth. It should also be straightforward to add bandwidth (and/or latency) spec attributes to the network modules, and update the perf modeling logic to include the network throughput in the overall throughput calculation.

**Comment by suyashbakshi** [comment]
Thanks! I will await @nellie-wu 's response to Q1.

For response to Q3: Since bandwidth is modelled at storage interfaces, would the PE to PE data transfer then be modelled as data transfer between private register files of the PEs?

**Comment by angshuman-parashar** [comment]
Re Q3: That is correct. Peer transfers will put pressure on the storage interfaces at the same level.

**Comment by suyashbakshi** [comment]
hello, any suggestion about question on wire length attribute?

Also, in the Aladdin plugin, although [this](https://github.com/Accelergy-Project/accelergy-aladdin-plug-in/blob/7fe410252d7aa515ed1d6dc8a29eaa2c4d5f3eaa/aladdin_table.py#L61) "if" condition only allows technology nodes of 40 and 45nm, but when computing the [wire energy](https://github.com/Accelergy-Project/accelergy-aladdin-plug-in/blob/7fe410252d7aa515ed1d6dc8a29eaa2c4d5f3eaa/aladdin_table.py#L282) there appears to be no influence of the technology node on the energy estimation. It appears to be only dependent on the datawidth and the wire length. Why isn't the technology node not being used for energy estimation? Or is it the case that the wire energy estimations between 40 and 45nm do not have any significant difference? 

If possible, it would be nice to know the references from where the values for [parameters](https://github.com/Accelergy-Project/accelergy-aladdin-plug-in/blob/7fe410252d7aa515ed1d6dc8a29eaa2c4d5f3eaa/aladdin_table.py#L282) such as "C_per_um", "alpha" are being derived from.

**Comment by nellie-wu** [comment]
Sorry for the delay. 

For wire length, it was defined as the average length from the GLB to the PEs. 

The wire energy for 40nm and 45nm were treated the same since the technology nodes are similar. Unfortunately, we cannot disclose the source of the cap information, as it is scaled based on some private information we have.  "Alpha" is the activity factor of the wire. We provide a common default, but the factor can be adjusted by assigning a different attribute value based on the designer's understanding of the component.

**Comment by suyashbakshi** [comment]
Thank you so much. Just one follow-up, if the wire length is defined as avg length between GLB and PEs, then does it also correspond to avg wire length between the PEs (or their register files)? Since @angshuman-parashar mentioned in a previous comment that peer transfers put pressure on storage interfaces at same level, I want to make sure I understand how the wire length is treated for peer-to-peer transfers, given that the same network that connects GLB to PEs, also connects PEs to each other.

**Comment by nellie-wu** [comment]
That is a great question. If the NoC is specified as between the GLB and PE array, it only accounts for the traffic from the GLB to PE register files, e.g., GLB<=>ifmap_spad. I would imagine that you need to add additional networks between the register files with length set appropriately for short peer-to-peer distance, such that the NoC can be picked up by timeloop to account for the peer-to-peer traffic.

**Comment by morainer** [comment]
Hello. After reading your dialogue, I have the following questions that I hope can be answered.
If my arch. yaml has 3 GLBs (ifmap_glb, weight_glb and psum_glb) and 1 PE_ Array, the following connection will be formed: ifmap_ glb<==>weight_ glb、weight_ glb<==>psum_ glb、psum_ glb<==>PE_ array.  But how can I control the three GLBs to connect only to the lowest PE array? In other words, the connection should be formed: ifmap_ glb<==>PE_ array、weight_ glb<==>PE_ array、psum_ glb<==>PE_ Array, while removing ifmap_ glb<==>weight_ glb、weight_ glb<==>psum_ glb.

**Comment by nellie-wu** [comment]
I think the networks need to connect in the order of specified storage levels and cannot be removed (@angshuman-parashar please correct me if there are ways to get around this). However, you can set the networks between the glbs to be zero cost, and assign nonzero cost to the `innermost-glb<=>PE_array` NoC to mimic the parallel glbs . Note that the `innermost-glb<=>PE_array` NoC includes all traffic for all different datatypes.

**Comment by suyashbakshi** [comment]
@nellie-wu The "eyeriss_like" example uses 2mm for the NoC. May I ask where the information about wire length was derived from?

**Comment by nellie-wu** [comment]
It is a rough estimate based on the die photo presented in the Eyeriss paper: http://www.rle.mit.edu/eems/wp-content/uploads/2016/11/eyeriss_jssc_2017.pdf

**Comment by suyashbakshi** [comment]
I have a question about the "network ingresses".  See the example architecture below, with 256 PEs, each with a register file and a MACC unit, and a NoC connecting them (ignore the "SimpleMulticast" network class, the subclass "maccRFNoC" is a 1:1 network between each MACC and RF). I'm observing that the network "ingresses" for a convolution operation's Weight and Input operands are equal to the number of arithmetic operations, which makes sense. But the "ingresses" for Output operands are ALSO equal to the number of operations. Shouldn't for Output operand, there be twice as many ingresses as the operations, 1 for a read and another for an update? Is there a correct way to enable this behavior?

There appears to be some comment [here](https://github.com/NVlabs/timeloop/blob/5fa90845fced0782e6c40e5883b728d917068b86/src/model/topology.cpp#L799) about the networks accounting for the operations incurring double transfers for read-modify-write operation, but i'm not sure where (and how) that information is used. Could you please provide some clarification on this?

```
- name: PE
        local:
        - name: RegisterFile[0..255]
          class: regfile
          attributes:
            <other size and b/w attributes>
            network_read: RF <=> MACC NoC
            network_update: RF <=> MACC NoC

        - name: RF <=> MACC NoC
          class: SimpleMulticast
          subclass: maccRFNoC
          attributes:
            datawidth: 8
            action_name: transfer
            multicast_factor_argument: n_cols_per_row

        - name: MACC[0..255]
          class: intmac
          attributes:
            datawidth: 8
            network_operand: RF <=> MACC NoC
            network_result: RF <=> MACC NoC
```

**Comment by angshuman-parashar** [comment]
The following line is supposed to model the 2x amplification (minus the first read).

https://github.com/NVlabs/timeloop/blob/5fa90845fced0782e6c40e5883b728d917068b86/src/model/network-legacy.cpp#L268

**Comment by suyashbakshi** [comment]
Thank you. Is there any reason why the 2x amplification is not considered in the SimpleMulticast network? Or is one expected to instantiate a reduction tree like network to account for Output operand updates?

**Comment by angshuman-parashar** [comment]
That's right, the SimpleMulticast network is intended primarily for delivering inputs. I suppose we don't have any gates in the Topology code that prevents its use for outputs/partial sums. Maybe we should, but it's not trivial because we don't want to hard-code any of this in Topology. So we would have to implement some kind of capability feature for the network modules, and each module would export its capabilities (e.g., I can transport read-traffic vs. rw-traffic).

**Comment by suyashbakshi** [comment]
Thank you, that would be nice to have otherwise the energy measurements, specifically the wire energy computed will be smaller than expected because the updates are not being accounted for.

**Comment by Po0ria** [comment]
> I think the networks need to connect in the order of specified storage levels and cannot be removed (@angshuman-parashar please correct me if there are ways to get around this). However, you can set the networks between the glbs to be zero cost, and assign nonzero cost to the `innermost-glb<=>PE_array` NoC to mimic the parallel glbs . Note that the `innermost-glb<=>PE_array` NoC includes all traffic for all different datatypes.

@nellie-wu Is this assuming that those networks being manually instantiated? How can I zero out the energy consumption of a legacy network instantiated by Timeloop?

**Comment by angshuman-parashar** [comment]
@Po0ria unfortunately we don't have a shortcut to zero out the energy consumption of an auto-instantiated network.
