### ISSUE TITLE
Channel pruning

### ISSUE THREAD

**Issue by nivi1501** [NVlabs/timeloop#186]
Hi, 
  Is it possible to implement and analyze the effects of channel-wise, filter-wise and shape-wise pruning in Spareloop?
Paper- An Efficient Hardware Accelerator for Structured Sparse Convolutional Neural Networks on FPGAs (Refer to Figure 1)
Link- https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9130762&tag=1

**Comment by nellie-wu** [comment]
Yes, Sparseloop can model such sparsity patterns with the appropriate mappings, but such coarse-grained structured sparsity, e.g., channel-wise and filter-wise, can be more easily modeled as a change of tensor shape.  For example, if channel-wise pruning is applied, the workload can be modeled still as a dense workload with decreased number of channels.

**Comment by nivi1501** [comment]
Thanks a lot !
