### ISSUE TITLE
Assertion throws with empty constraint

### ISSUE THREAD

**Issue by aleczhanshi** [NVlabs/timeloop#19]
Hi there,

When I'm running `timeloop-mapper eyeriss-256.cfg' and get rid of all constraints, it throws the assertion below. Is there a basic set of constraints that have to be specified? If so, what are they? In more general, how should we go about get rid of all constraints (or any set of constraints)?

Thanks!

``` C++
WARNING: found neither a problem shape description nor a string corresponding to a to a pre-existing shape description. Assuming shape: cnn-layer.
MESSAGE: attempting to read problem shape from file: /scratch/cluster/zshi17/timeloop/problem-shapes/cnn-layer.yaml
Problem configuration complete.
Architecture configuration complete.
Using all available hardware threads = 24
Mapper configuration complete.
Initializing Index Factorization subspace.
  Factorization options along problem dimension R = 8
  Factorization options along problem dimension S = 8
  Factorization options along problem dimension P = 960
  Factorization options along problem dimension Q = 960
  Factorization options along problem dimension C = 6435
  Factorization options along problem dimension K = 6435
  Factorization options along problem dimension N = 1
Mapspace Dimension [IndexFactorization] Size: 2442415472640000
Mapspace Dimension [LoopPermutation] Size: 3252016064102400000
Mapspace Dimension [Spatial] Size: 64
Mapspace Dimension [DatatypeBypass] Size: 32768
timeloop-mapper: src/mapspaces/uber.hpp:142: void mapspace::Uber::Init(config::CompoundConfigNode): Assertion `de_cumulative_prod == 1' failed.
zsh: abort (core dumped)  timeloop-mapper eyeriss-256.cfg
```

**Comment by angshuman-parashar** [comment]
What happened here is that the mapspace size overflowed a 128-bit integer. Sorry about that - I'll put in a fix. In the meantime, you should really put in some constraints. With a mapspace this large (even if it were to fit within 128 bits), it's improbable that any of the existing search heuristics will arrive at a near-optimal solution in any reasonable amount of time (even though many of the mappings will eventually get pruned). In general you should only use a zero-constraint setup with very simple toy architectures. For realistic architectures - it's unlikely for a hardware accelerator to have that much flexibility. At the same time, it's tricky to recommend universal guidelines for constraints. Your best bet would be to start with a well-known baseline, slowly relax constraints and see how that changes things.

**Comment by aleczhanshi** [comment]
@angshuman-parashar I think it answers my question, thanks! Another question related to your answer is that, I assume the well-known baselines that you mentioned are the dataflows (and the architecture) of Eyeriss and Simba, for example. Do you have them specified anywhere in the codebase?

**Comment by angshuman-parashar** [comment]
There are simba, eyeriss and chen/asplos2014 architecture configs in the configs/mapper directory.

**Comment by aleczhanshi** [comment]
@angshuman-parashar Thanks! I'm opening up another issue for another question, but thanks for the quick response!
