### ISSUE TITLE
Memorry access read write energy

### ISSUE THREAD

**Issue by Omar-Abdul-Aziz** [NVlabs/timeloop#199]
Hello, It's posiible to modify the time and energy of the memory access in Timeloop for the memories between the Main Memory and the PE? 
For example, I can test the influence of using a memory two or three faster in the reading?

Thank you

**Comment by angshuman-parashar** [comment]
For energy you can do it by altering the Accelergy tables, or you can also override the Accelergy data by specifying `vector-access-energy` for each memory level in `arch.yaml`.

For performance, what do you mean by "faster"? Initial access latency, or throughput? If it's throughput you'll want to change the `bandwidth` attribute (specified in words-per-cycle that the memory can deliver). If it's latency then Timeloop doesn't model that today. And for large enough workloads it shouldn't be a huge factor.

**Comment by nellie-wu** [comment]
There are two places that you might want to check:

1. Did you reinstall the Aladdin plug-in after changing the code? If not, you need to reinstall it to reflect the change.
2. Is your MAC a compound component class? If so, you need to make sure that the `latency` attribute of MAC is correctly propagated to the subcomponents' `latency` attribute in the compound component definition. 

FYI, you can add your table-based plug-in for your own energy numbers. We have a template for doing that here: https://github.com/Accelergy-Project/accelergy-table-based-plug-ins

**Comment by Omar-Abdul-Aziz** [comment]
Thank you for your quick responce!
It works

**Comment by Omar-Abdul-Aziz** [comment]
In the set of table template, the always precised the energy of the read action of the DRAM, SRAM... 
How accelergy calculate the energy of the write action? It takes the same energy for both? Is it possible to define the energy of the write action in the tables ?
