### ISSUE TITLE
More sample configs?

### ISSUE THREAD

**Issue by dingqingy** [NVlabs/timeloop#2]
Hi @angshuman-parashar,

Great simulator! Thanks for your hard work. It seems like that the current sample config specifies a weight stationary dataflow. I am interested in exploring other dataflows as well. Can you provide some more sample configs for other popular dataflows like output stationary and row stationary? Or can you provide more documentation on how certain map constraints specify certain dataflows? 

Thanks!

**Comment by angshuman-parashar** [comment]
Acknowledged, and thank you for your interest. We do have other cfgs internally, but we need to vet them carefully before a public release. Our hope is to be able to do that within the next month.

**Comment by angshuman-parashar** [comment]
Added eyeriss-256 and eyeriss-1024 configs.

**Comment by dingqingy** [comment]
Hi @angshuman-parashar,

Thank you for sharing more configs. Can you explain why there is a dummy buffer with size zero in the eyeriss configs?
