### ISSUE TITLE
Question about problem-shapes/cnn-layer.yaml 

### ISSUE THREAD

**Issue by kim-sunghoon** [NVlabs/timeloop#22]
Hi, Thank you for the awesome tool!
I have a question about problem-shapes / cnn-layer.yaml.
How to change Projection to run Depthwise Separable Convolution of MobileNet, not Standard Convolution?

like pytorch code 
```python
class DWConv3x3(nn.Module):
    def __init__(self, nin, nout):
        super(DWConv3x3, self).__init__()
        self.depthwise = nn.Conv2d(nin, nin, kernel_size=3, padding=1, groups=nin)
    def forward(self, x):
        out = self.depthwise(x)
        return out
```

Thank you in advance!

**Comment by angshuman-parashar** [comment]
I would start by evaluating it as two back-to-back loop nests, the first doing the depth-wise conv, and the second doing the point-wise operation. For each, you can write your own problem-shape (create two new yamls in problem-shapes/), or you can just re-parameterize the cnn-layer shape to model those operations (set K=1 to model depth-wise and R,S=1 to model point-wise). Then fire timeloop separately to solve each problem.

Now, if an intermediate storage level in your architecture is large enough to completely host the intermediate activations without moving them in/out of DRAM, you can force Timeloop to emulate that behavior. In the Constraints specification, set the bypass flag for all storage levels outwards of that level, including DRAM, and force the temporal tiling factors for the problem dimensions that affect intermediate activation dimensions (N,P,Q,C) to 1. In theory, you could fuse the two stages at a finer granularity but we don't support that today.

**Comment by kim-sunghoon** [comment]
I appreciate your thoughtful answer :) 👍

**Comment by ChenpingHU** [comment]
We can set K=1 for depth-wise convolution, but how can we reflect the fact that the number of output channels is not coupled to K dimension, rather coupled to C dimension.
