### ISSUE TITLE
Seeking Guidance on Updating to the Latest Version of Timeloop

### ISSUE THREAD

**Issue by xpww** [NVlabs/timeloop#235]
Dear Timeloop Maintainers,

I hope this message finds you well. I am relatively new to Timeloop and have been working on a project that utilizes your framework. First and foremost, I want to express my appreciation for the great work you've done with Timeloop.

Recently, I noticed that there have been updates to the Timeloop project on GitHub. I am keen to incorporate the latest version into my project, but I'm encountering some challenges with the installation process. While I successfully followed the installation instructions provided on the project's website (https://accelergy.mit.edu/infra_instructions.html), it appears that these instructions may be outdated in light of the recent updates to Timeloop.

To navigate this situation, I have a few questions:

How can I obtain the latest version of Timeloop? Is it as simple as following the installation tutorial on the website and recompiling, or are there additional steps I should be aware of?
I understand that keeping documentation up-to-date can be a significant challenge, and I appreciate your efforts in maintaining the project. Your guidance on this matter will be invaluable to me as I aim to seamlessly integrate the latest version of Timeloop into my project.

Thank you for your time and assistance. I look forward to your guidance and am eager to continue working with Timeloop.

Best regards

**Comment by angshuman-parashar** [comment]
Are you using the Docker image or building natively?

**Comment by xpww** [comment]
> Are you using the Docker image or building natively?

I building it natively.

**Comment by angshuman-parashar** [comment]
The instructions should work for a native build. Are you running into any problems? You'll get the latest master, which does have some experimental features. You can also check out the latest stable release, which as of this message's date is v3.0.3.

**Comment by xpww** [comment]
> The instructions should work for a native build. Are you running into any problems? You'll get the latest master, which does have some experimental features. You can also check out the latest stable release, which as of this message's date is v3.0.3.

Thank you very much！now my problem is solved and I have upgraded to v3.0.3 version
