### ISSUE TITLE
Problems on installing timeloopfe

### ISSUE THREAD

**Issue by matthew-mx** [NVlabs/timeloop#248]
I have successfully installed Timeloop+Accelergy v4, but when I try to install timeloopFE,  I have such problems below:
----------------------------------------------------------------------------------------------------------------------------------
Processing ./timeloopfe
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
INFO: pip is looking at multiple versions of timeloopfe to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement accelergy>=0.4 (from timeloopfe) (from versions: none)
ERROR: No matching distribution found for accelergy>=0.4

**Comment by tanner-andrulis** [comment]
Install & update Accelergy. See the install_accelergy Make command in https://github.com/Accelergy-Project/accelergy-timeloop-infrastructure
