### ISSUE TITLE
More operands for problem.yaml

### ISSUE THREAD

**Issue by AsicDyc** [NVlabs/timeloop#251]
Hi,

Thank you for providing such a useful tool.
Just want to know does timeloop support other operands like matrix multiplication or depth-wise convolution? Are there any tutorials or examples for these operands?
Thanks for your assistance.

**Comment by angshuman-parashar** [comment]
Yes. GEMM is already provided as a problem shape in https://github.com/NVlabs/timeloop/blob/master/problem-shapes/gemm_ABZ.yaml. Please watch our video tutorials in order to understand how to describe problem shapes.

**Comment by AsicDyc** [comment]
Thanks a lot for your prompt reply. What about depth-wise convolution? The calculation methods between depth-wise convolution and traditional convolution differ, so simply describing depth-wise convolution as a cnn_layer type in prob.yaml would lead to issues.

**Comment by angshuman-parashar** [comment]
See if this answers your question: https://github.com/NVlabs/timeloop/issues/22

**Comment by AsicDyc** [comment]
Thanks a lot! It helps me.
