### ISSUE TITLE
What is updated in v4 version？

### ISSUE THREAD

**Issue by Pupu792** [NVlabs/timeloop#264]
The reference to v3 is given in the readme, but the content in the documentation link is Timeloop+Accelergy v4. I want to konw what has changed in v4

**Comment by angshuman-parashar** [comment]
We are preparing a new Timeloop release that we will post in the coming 1-2 weeks. The release notes will describe the new features, including the new easier-to-describe v4 architecture spec format. All v3 YAMLs should be backwards-compatible.
