### ISSUE TITLE
Modelling of Batch Matrix Multiplication

### ISSUE THREAD

**Issue by Nerotos** [NVlabs/timeloop#275]
Hello,

is it possible to run a batch matrix multiplication operation, i.g. a matrix multiplication where a matmul of A(b,i,k) and B(b,k,j) gives an output matrix C(b,i,j)?. See also [the PyTorch documentation.](https://pytorch.org/docs/stable/generated/torch.bmm.html). Specifically I would be interested in a way to model this without decomposing it into b matrix multiplications. Thanks in advance!

**Comment by Nerotos** [comment]
Thanks! Can I also use a conv2d template and set P = B (so use the number of output rows as the batch size)? According to the original paper, a matrix-matrix operation can be described with p=q=r=s=1, so I'm wondering if I am thinking in the correct direction.

**Comment by angshuman-parashar** [comment]
No, because P only affects inputs and outputs in conv2d (not weights), while in your formulation b affects all 3 tensors.

In general I wouldn't advise using such problem shape transpositions unless you really know what you are doing. Constraints may not map cleanly.
