### ISSUE TITLE
Running gemm simulation on architecture

### ISSUE THREAD

**Issue by aleczhanshi** [NVlabs/timeloop#31]
Hi there,

I see there's problem descriptor for gemm (attached below). Is there any template that i can use to specify my shape (M, N and K) and run on any of the architecture

```
shape =
{
  name = "gemm";
  dimensions = [ "M", "N", "K"];
  data-spaces =
  (
    {
      name = "A";
      projection = [ "M", "K" ];
    },
    {
      name = "B";
      projection = [ "N", "K"];
    },
    {
      name = "C";
      projection = [ "M", "N" ];
    },
    {
      name = "D";
      projection = [ "M", "N"];
      read-write = True;
    }
  );
};
```

**Comment by angshuman-parashar** [comment]
I'm afraid I don't understand the question. Are you looking for a way to specify a particular instance of GEMM? Just add a YAML with `problem: shape: gemm M:256 N:256 K:256` or some such. You should be able to run it against any of the architectures. However, you do need to set up GEMM-specific mapspace constraints.

**Comment by aleczhanshi** [comment]
@angshuman-parashar Thanks. I think that's basically what I'm asking. I find that architectures like eyeriss and simba are specific to CNNs, where they have the inputs, weights, and output buffer. If I were to run gemm on eyeriss, for example, is there a mapspace that I can start from?

**Comment by angshuman-parashar** [comment]
Could you write one and contribute it to the project? :-)
