### ISSUE TITLE
Some questions on the memory energy methodology

### ISSUE THREAD

**Issue by egiacomin** [NVlabs/timeloop#36]
Hello,

I am currently using Timeloop & Accelergy to evaluate some CNN architectures.
I am only using Table based energy for the computation, but I am having troubles understanding how Timeloop & Accelergy are using these energy numbers:

**1-** When using a specific layer (for the problem) description, I can see in the .stats.txt file (I am only showing the important lines here):

```
Level 2
-------
=== MainMemory ===
....
        Vector access energy : 8.14 pJ
...
    Weights:
...
        Energy (per-scalar-access)               : 1.02 pJ
```
The vector access energy (8.144 pJ) is the one I used in the .csv table file, so up to there, all is working. And we have the energy per-scalar-access which is 8.144/8=1.02 pJ as I only use 8-bit data width in my design.

However, 1.02 pJ is used for all weights/input activations and outputs, while I have a separate read a write values in my .csv file. When only having the "read" or the "write" line in my csv, Timeloop will use this value, but when having both, Timeloop will only use the "higher" value. Am I missing something here? I am using the Docker container (https://github.com/Accelergy-Project/timeloop-accelergy-tutorial), so maybe it's outdated?

**2-** When using the exact same design, but only changing the problem parameters (like only having 1 filter 3x3 and 1 image 3x3), the .map.stats file looks like:

```
Level 2
-------
=== MainMemory ===
....
        Vector access energy : 8.14 pJ
...
    Weights:
...
        Energy (per-scalar-access)               : 1.81 pJ

    Inputs:
...
        Energy (per-scalar-access)               : 1.30 pJ
```

So this time, the 8.144 pJ is used for the vector access, but the energy per scalar access is different (while the design is exactly the same). Is that expected?

Thanks!

**Comment by angshuman-parashar** [comment]
Can you please attach the YAMLs (for both experiments) so that we can reproduce? Please include a small txt file with the precise command lines used to invoke each experiment.

**Comment by egiacomin** [comment]
[timeloop_issue.zip](https://github.com/NVlabs/timeloop/files/4767411/timeloop_issue.zip)

Here you go. Please let me know if you have trouble running this testcase.

**Comment by angshuman-parashar** [comment]
You're seeing fragmentation with your small_layer. The DRAM block_size is 8, which means you'll pay the energy cost of fetching 8 words even if you fetch less than that. Your Weight tensor is 9 words in size, which means it will consume ceil(9/8) = 2 DRAM vector accesses, consuming a total of 8.14*2 = 16.28pJ. Scalar energy is simply the net cost you end up paying per scalar word, which in this case is 16.28pJ/9 = 1.81pJ.

For input activations, the math is: 25 scalar words, so ceil(25/8) = 4 DRAM vector accesses costing 8.14*4 = 32.56pJ, which means per-scalar cost is 1.3pJ.

As you increase problem size these fragmentation effects will be much less pronounced.

**Comment by egiacomin** [comment]
@angshuman-parashar really appreciate the explanation. That makes total sense now.
