### ISSUE TITLE
number of PEs in eyeriss-256.yaml

### ISSUE THREAD

**Issue by Diksha-Moolchandani** [NVlabs/timeloop#41]
The number of MACs in the config file of eyeriss is taken 256 while in the original eyeriss paper, it is 168.
Any specific reason for the same?

**Comment by angshuman-parashar** [comment]
I believe one advantage of the 168 number is that it is divisible by 3, which is a common filter size. This leads to potentially higher utilization for the row-stationary dataflow. As far as Timeloop is concerned it's just a parameter. Please feel free to change it to suit the experiment you are trying to run.

**Comment by Diksha-Moolchandani** [comment]
thanks for the explanation.
