### ISSUE TITLE
best mapping found by mapper

### ISSUE THREAD

**Issue by hanloveland** [NVlabs/timeloop#43]
Hello,

When working on the timeloop and timeloop-accelergy exercise, I have a question for the best mapping found by the mapper.
As far as I know, the mapper uses multi-threading to reduce the run time of timeloop. So, I guess that the timeloop picks the most optimized value among the results of the mapper executed in multiple threads. The followed result is the mapper's result.  
Finally, the mapper selected the result of TID 0 (7.405pj) as the best mapping. However, as you can see from the results below, Opt.energy of TID2(6.045 pJ), TID3(6.372 pJ), and TID7(6.228 pJ) are lower than the best mapping found by the mapper.
Could you tell me why the mapper selected the result of TID0 as the best mapping?

```

================================================================================
                                TIMELOOP MAPPER
================================================================================
TID      Total    Invalid      Valid    Consec.       Last   Opt.util Opt.energy
                                        invalid     update
--------------------------------------------------------------------------------
- 0       7579       6837        742          0        500    100.00%      7.405
- 1       5716       5193        523          0        500    100.00%      6.045
- 2       8820       8199        621          0        500    100.00%      6.372
- 3       8804       8114        690          0        500    100.00%     16.086
- 4       7167       6586        581          0        500    100.00%     17.626
- 5       6600       6069        531          0        500    100.00%     12.765
- 6       9461       8951        510          0        500    100.00%     12.759
- 7       9426       8918        508          0        500    100.00%      6.228

Summary stats for best mapping found by mapper:
  Utilization = 1.00 | pJ/MACC =    7.405
```

**Comment by angshuman-parashar** [comment]
Are you running the latest codebase? And which example is this?

**Comment by angshuman-parashar** [comment]
@hanloveland could you please confirm if your issue is resolved?

**Comment by hanloveland** [comment]
Thanks. The mapper is properly working now after I got a new version timeloop.
