### ISSUE TITLE
Area Details not present in stats.txt file

### ISSUE THREAD

**Issue by madnan92** [NVlabs/timeloop#44]
Hi @angshuman-parashar 
Thanks for the great tool.
I am using timeloop with accelergy which is giving me ART.yaml and ART_summary.yaml file but in the final stats file I am not getting the overall area that my architecture is consuming.
In the stats file it always gives me Area=0 mm^2
Is it normal? Or do I need to to do something to make it work?

**Comment by nelliewu95** [comment]
Please make sure that you are using the most up-to-date version of Timeloop. If you are using the most up-to-date version, it is possible that the area of your architecture is too small and the area mm^2 is rounded to zero. You check out the individual component areas (arithmetic and storage type components) and also `Total topology area` number towards the end of the stats file, they are all in um^2.

**Comment by angshuman-parashar** [comment]
@madnan92 could you please confirm if your problem is resolved?

**Comment by madnan92** [comment]
@angshuman-parashar  sorry for the late reply as I didn't have access to the system.
I tried the latest commit with sample.yaml file using accelergy and cacti but still I am not getting the area stats.
Please find attached the timeloop-mapper.stats.txt file for sample.yaml file.
[timeloop-mapper.stats.txt](https://github.com/NVlabs/timeloop/files/5098674/timeloop-mapper.stats.txt)

**Comment by madnan92** [comment]
Sorry, it worked.
Thanks
