### ISSUE TITLE
Timeloop crashes when "diagnostics: True" in the mapper.yaml file

### ISSUE THREAD

**Issue by egiacomin** [NVlabs/timeloop#45]
Hello,

I am currently using the latest Timeloop commit and when setting" diagnostics: True" in the mapper file, Timeloop is crashing:

`================================================================================
                                TIMELOOP MAPPER
================================================================================
TID      Total    Invalid      Valid    Consec.       Last   Opt.util Opt.energy
                                        invalid     update
--------------------------------------------------------------------------------
  0          1          1          0          1          0
  1          4          4          0          4          0terminate called after throwing an instance of 'std::out_of_range'  4          0
  3          4          4          0        terminate called recursively
  4          1          1          0          1          0              Aborted (core dumped)4          4          0          4          0`

When setting the value to "False", Timeloop runs fine.
This was not the case a few commits ahead (I think I was running the commit e3dbf0913c040e598dbaf5b9a6819295aa96c833, or the one just after, and I did not have this behavior).
I attached a testcase in case you want to reproduce the issue on your end. Let me know if you have the same problem as well, or if I am missing something.

[testcase_files.zip](https://github.com/NVlabs/timeloop/files/4926609/testcase_files.zip)

**Comment by angshuman-parashar** [comment]
This should be fixed now. Could you please verify and close the issue if fixed?

**Comment by egiacomin** [comment]
It's working fine now. Thanks for the quick fix.
