### ISSUE TITLE
Is it possible to describe an array of "arrays"?

### ISSUE THREAD

**Issue by egiacomin** [NVlabs/timeloop#48]
Hello,

I am trying to describe an array of arrays in Timeloop. As an example, what if I want to study the ISAAC architecture considering several IMAs instead of a single one (as specified here: https://github.com/Accelergy-Project/timeloop-accelergy-exercises/blob/master/baseline_designs/example_designs/simple_pim/arch/system_PIM.yaml)?

Right now, for a single IMA (128*128 array), the arch. description is:

          subtree:
            - name: PE[0..16383]
              local:                 # "local" contains physical instantiations
                - name: scratchpad
                  class: memcell_storage  # definitions of the compound classes can be found under "components" folder
                  attributes:
                    width: 16       # width in bits
                    depth: 1
                    meshX: 128        # number of components in the X dimension (PE rows)
                    meshY: 128        # number of components in the Y dimension (PE cols)
                - name: mac
                  class: memcell_compute
                  attributes:
                    datawidth: 16   # datawidth in bits
                    meshX: 128        # number of components in the X dimension (PE rows)
                    meshY: 128        # number of components in the Y dimension (PE cols)

I'd like to consider a 4*4 IMA array, so I am wondering how to use the meshX/meshY parameters as we have "2 levels of mesh" (1 for the number of IMAs and 1 for the number of elements within 1 IMA).
I was thinking of something like this, but I am running into errors (as the meshX/meshY have to correspond to the PE_Array dimensions, but I'd also like to specify that each IMA has some meshX/meshY dimensions):

          - name: PE_Array[0..3]
            subtree:
            - name: PE[0..16383]
              local:                 # "local" contains physical instantiations
                - name: scratchpad
                  class: memcell_storage  # definitions of the compound classes can be found under "components" folder
                  attributes:
                    width: 16       # width in bits
                    depth: 1
                    meshX: 128        # number of components in the X dimension (PE rows)
                    meshY: 128        # number of components in the Y dimension (PE cols)
                - name: mac
                  class: memcell_compute
                  attributes:
                    datawidth: 16   # datawidth in bits
                    meshX: 128        # number of components in the X dimension (PE rows)
                    meshY: 128        # number of components in the Y dimension (PE cols)

Thanks!

**Comment by angshuman-parashar** [comment]
You'll have to include a dummy storage unit at the PE_Array[0..3] level. Set its size to 0, set bypasses for all tensors in the arch_constraints, and also set all temporal (but not spatial) factors to 1 for all dimensions.
Additionally I'm not 100% sure if the meshX/meshY attributes need to be relative (in which case your 128/128 numbers are fine) or absolute (in which case they need to be changed to 512/512). @poant could you comment?

**Comment by poant** [comment]
In this case, meshX/meshY has to be absolute (512/512). Currently the multiplication factor only applies to the number of instances in the hierarchy, not the other attributes.

**Comment by egiacomin** [comment]
Thanks to both of you.
Indeed, the meshX/meshY attributes have to use the multiplication factor.
