### ISSUE TITLE
how can I get some help to study these config attribute meaning?

### ISSUE THREAD

**Issue by hbhbts** [NVlabs/timeloop#50]
Hi,
    I'm fresh to study the timeloop tools. And I cann't find some user guide to understanding the examples. Specailly about the config attribute, how many attribute do they have and what are they. Could you give some user guide?

**Comment by angshuman-parashar** [comment]
Thanks for your interest. Please watch our ISCA 2020 tutorial videos and presentations at http://accelergy.mit.edu/tutorial.html. That should get you started.
