### ISSUE TITLE
config format

### ISSUE THREAD

**Issue by cnjsdfcy** [NVlabs/timeloop#51]
Hi,

Timeloop supports both libconfig and yam formats for input configurations, will it be unified?

Thanks,
Cai Yu

**Comment by angshuman-parashar** [comment]
They are already unified in the sense that Timeloop has a common wrapper library around both formats that provides a consistent API to the rest of the tool. This gives us the agility to support other formats in future if needed. However, moving forward we are using YAML as our primary config language, with libconfig relegated to legacy status.

**Comment by cnjsdfcy** [comment]
Got it, Thanks~
