### ISSUE TITLE
Design Space Example Configuration

### ISSUE THREAD

**Issue by madnan92** [NVlabs/timeloop#57]
Hi,

I am just trying to use design space application part of timeloop.
It seems like it just needs multiple architecture and problem files. What about the mapping and constraints file in that case?
Is there any configuration example available for design space exploration that can help.

**Comment by angshuman-parashar** [comment]
I apologize, the design space application is an experimental feature and is not fully supported. I recommend running design space searches in an outer loop (e.g. in a Python script) around Timeloop. You can use the scripts located in the scripts/ directory to interface with Timeloop from Python.

**Comment by madnan92** [comment]
Thanks.
