### ISSUE TITLE
Issue while building Timeloop

### ISSUE THREAD

**Issue by arkodutt** [NVlabs/timeloop#58]
I ran into a problem while building timeloop. How can I resolve this? I already installed all prerequisites. I am using Ubuntu 16.04.

/usr/include/c++/5/bits/hashtable_policy.h:85:34: **error**: no match for call to ‘(const std::hash<boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<128u, 128u, (boost::multiprecision::cpp_integer_type)0u, (boost::multiprecision::cpp_int_check_type)0u, void> > >) (const boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<128u, 128u, (boost::multiprecision::cpp_integer_type)0u, (boost::multiprecision::cpp_int_check_type)0u, void> >&)’
  noexcept(declval<const _Hash&>()(declval<const _Key&>()))>

**Comment by angshuman-parashar** [comment]
What gcc version are you using? Specific libboost versions are only happy with specific gcc versions.

**Comment by arkodutt** [comment]
I am using gcc 5.4.0.

**Comment by angshuman-parashar** [comment]
Yeah that's a really old version that we haven't tested building against in a long time. Please consider upgrading your distribution.
