### ISSUE TITLE
How Timeloop takes latency of different types of memories into account while measuring performance? 

### ISSUE THREAD

**Issue by 05Tushar** [NVlabs/timeloop#60]
In cycle-accurate simulators such as Gem5, we can replace one memory (say SRAM) with another (say STTRAM). The difference in their latency and capacity affects the overall performance (measured as cycle-count). Can we do something like that in timeloop and will it have an effect on the performance?
Consider an analogy: how would the cycle-count change if I were to replace an RF with a larger RF. This would surely change the performance because accesses to DRAM will be reduced, but each RF access now takes more latency. 
Thank you in advance!

**Comment by 05Tushar** [comment]
There was an example in this exercise too [timeloop-accelergy-exercises](https://github.com/Accelergy-Project/timeloop-accelergy-exercises/tree/7252362fc514af7e5bb5442e1d66c0bc522999cc/exercises/timeloop%2Baccelergy) where we changed the type of DRAM from LPDDR4 to HBM2 but it had no effect on performance (number of cycles) although they have different latencies and bandwidths.

**Comment by angshuman-parashar** [comment]
Timeloop's performance modeling is bandwidth-based, and the user configures the bandwidth using the component attributes. LPDDR4 and HBM2 do not "have" an inherent baked-in bandwidth, the bandwidth depends on the number of channels, bits per channel, clock speed etc. All these are parameters abstracted into the user-specified "bandwidth" attribute in a Timeloop memory component, and as far as performance modeling is concerned this attribute dictates the component's capabilities. So if you provision lower DRAM bandwidth, workloads may begin to get bottlenecked by that bandwidth and throttle down. The technology (i.e., LPDDR4 vs. HBM2) is used to invoke the appropriate Accelergy plugin for energy modeling.

Regarding your small-vs-large RF example: Again, throughput-based modeling is sensitive to bandwidth, not latency. If your larger RF (despite its increased latency) is able to initiate the same #requests per cycle as your smaller RF, then in general your steady-state performance should remain unchanged. This steady-state performance is what Timeloop models using the bandwidth attribute. Yes, the initial pipeline fill/drain latency is not accounted for in today's model, but this is a minor tax for most realistically-sized network layers.

**Comment by 05Tushar** [comment]
Thank you so much sir for the clarification!
