### ISSUE TITLE
hardware extension

### ISSUE THREAD

**Issue by TravisDai** [NVlabs/timeloop#62]
Hi, I can see that the /arch/ directory within timeloop contains the description of the hardware architecture. however, I do not see any details described about the latency and energy, how can we get the cycles number ? Besides, if I want to do the extension of the hardware, how can I modify the files?

Thanks.

**Comment by angshuman-parashar** [comment]
Hi, thank you for your interest. In case you are getting started with the tool, I *strongly* recommend going through our tutorial series here: http://accelergy.mit.edu/tutorial.html.
