### ISSUE TITLE
Support for 3D CNN

### ISSUE THREAD

**Issue by Diksha-Moolchandani** [NVlabs/timeloop#64]
Hi,

Do you have some preliminary support for 3D CNNs in timeloop?

thanks

**Comment by Diksha-Moolchandani** [comment]
I have an idea:

Say I have an input of 5x5x4 and a filter of 3x3x3. In a 3D convolution, it would produce an output of 2x2x2.

I can break this into two 2D convolutions,

1. Input 5x5x3 (first 3 channels - 1,2,3) with filter 3x3x3x, I get an output of 2x2x1
2. Input 5x5x3 (3 channels starting from 2nd channel - 2,3,4) with filter 3x3x3x, I get an output of 2x2x1

Anyways the exact values don't matter. So a 3D convolution layer can be broken into two 2D convolution layers. I can define two problem.yaml files and run them in timeloop separately.

Is this the right way of doing this?

**Comment by poant** [comment]
Hi,

Timeloop supports 3D convolution natively. To run 3D convolutions, you will need to provide a different problem shape yaml instead of using the "cnn-layer.yaml" under /problem-shape/.

See attached yaml as an example.


`
shape:

  name: "3d-CNN-Layer"
  dimensions: [ R, S, T, P, Q, F, C, K, N ]
  coefficients:
    - name: Wstride
      default: 1
    - name: Hstride
      default: 1
    - name: Dstride
      default: 1
    - name: Wdilation
      default: 1
    - name: Hdilation
      default: 1
    - name: Ddilation
      default: 1
     
  data-spaces:
    - name: Weights
      projection:
        - [ [C] ]
        - [ [K] ]
        - [ [R] ]
        - [ [S] ]
        - [ [T] ]
    - name: Inputs
      projection:
        - [ [N] ]
        - [ [C] ]
        - [ [R, Wdilation], [P, Wstride] ] # SOP form: R*Wdilation + P*Wstride
        - [ [S, Hdilation], [Q, Hstride] ] # SOP form: S*Hdilation + Q*Hstride 
        - [ [T, Ddilation], [F, Dstride] ] # SOP form: T*Ddilation + F*Dstride 
    - name: Outputs
      projection:
        - [ [N] ]
        - [ [K] ]
        - [ [Q] ]
        - [ [P] ]
        - [ [F] ]
      read-write: True
`

**Comment by Diksha-Moolchandani** [comment]
Thanks a lot
