### ISSUE TITLE
Using accelergy with timeloop

### ISSUE THREAD

**Issue by Diksha-Moolchandani** [NVlabs/timeloop#66]
Hi,

I installed accelergy and "which accelergy" works fine. Now when I install timeloop, I provided the pat symbolic link as given in the readme and then built with scons --accelergy and scons -j4. 

I also have timeloop running on another machine where I followed the same steps except scons --accelergy.

In both of them I am getting the same energy per macc output. I am unsure if the first version is using accelergy or it is using the default pat model. 

Can you please guide me here? Is the default pat symbolic link needed in case of running with accelergy?

**Comment by nellie-wu** [comment]
`scons --accelergy` is the command for compiling Timeloop with Accelergy and `scons -j4` is the command for compiling without Accelergy. 

So in your case, please only run `scons --accelergy`  command.

**Comment by Diksha-Moolchandani** [comment]
Thanks a lot
