### ISSUE TITLE
Recommendations on the type of search algorithm

### ISSUE THREAD

**Issue by Diksha-Moolchandani** [NVlabs/timeloop#68]
Hi,

I needed some insights for which search algorithm to use when. I observed that linear-pruned is way faster than random-pruned for some architectures. And hence I am more inclined to using linear-pruned.

Can you please let me know the advantages and disadvantages of these?

**Comment by angshuman-parashar** [comment]
You can use linear-pruned for smaller mapspaces. For larger mapspaces random-pruned is more likely to arrive at a near-optimal mapping.

**Comment by Diksha-Moolchandani** [comment]
Thanks
