### ISSUE TITLE
Cannot compile the codes

### ISSUE THREAD

**Issue by mbadaroglu** [NVlabs/timeloop#69]
I got the following error while compiling the source using "scons -g4".
g++: error: unrecognized command line option ‘-std=c++14’
I use g++ 4.5.2.

How can I compile?

Thanks,
-Mustafa

**Comment by angshuman-parashar** [comment]
That is an extremely old version of gcc. The current release version is 10.2, and most Linux distros are shipping 9.x. We use some modern C++14 features so it's not possible to downgrade. Unfortunately the only solution is to upgrade your gcc version.

**Comment by mbadaroglu** [comment]
Hi Parashar, I updated the gcc compiler to v10.1, which is relatively recent. Somewhat this gcc version does not recognize -std=c++14 flag as well. I will compile v10.2 to see what happens. Before this why does it still cause a compilation error although gcc version is relatively recent?
