### ISSUE TITLE
Is there a reason EnableLinkTransfers needs to be env variable than in model/mapper config file?

### ISSUE THREAD

**Issue by vmiheer** [NVlabs/timeloop#71]
https://github.com/NVlabs/timeloop/blob/db033564c443c2dfa519427034e7cc2ceece3fda/src/loop-analysis/nest-analysis.cpp#L48

**Comment by angshuman-parashar** [comment]
`no_link_transfer` is now exposed as a per-level YAML flag. The global env variable to override everything still exists as a debugging aid, but we do not expect most users to use it.
