### ISSUE TITLE
Small question about specification of DRAM bandwidth

### ISSUE THREAD

**Issue by vmiheer** [NVlabs/timeloop#75]
Hi I have couple of small questions,
1. In ML architecutres, is DRAM necessarily clocked at same clock as the SOC?
2. If not, while specifying (read|write)-bandwidth in yaml files, given that words/cycle is unit of bandwidth, one needs to provide that number assuming differences in DRAM and SoC frequencies?

**Comment by angshuman-parashar** [comment]
1. Not at all, DRAM clocks are usually different from the SoC clock.
2. Yes, you need to factor the clock speed differences into the bandwidth parameter. So the words/cycle should be the effective words per *SoC* cycle that the DRAM can deliver.

**Comment by vmiheer** [comment]
Awesome thank you!
