### ISSUE TITLE
what  does it mean when Factor=0?

### ISSUE THREAD

**Issue by ChenpingHU** [NVlabs/timeloop#77]
I found that there are some dimension factors that are equal to 0 in the constraint files used by some exercises. So how do we understand this? Thank you!
![image](https://user-images.githubusercontent.com/44984622/110345828-425ad780-802f-11eb-9c7e-dc799fc424fe.png)

**Comment by angshuman-parashar** [comment]
0 is a special code that tells the mapper to apply the entire problem dimension to that factor. So if R=3 in the problem spec, then the weights_spad will use R=3 in this example.
