### ISSUE TITLE
Mapper Diagnostic Mode results in Segfault

### ISSUE THREAD

**Issue by ncrago** [NVlabs/timeloop#8]
When using the mapper configuration flag "diagnostics: True", Mapping.PrettyPrint() throws an exception resulting from segfault.  

"terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 8) >= this->size() (which is 0)
Aborted (core dumped)"

**Comment by angshuman-parashar** [comment]
Fixed in commit 75079f0f140ce1ae0ce359045792c9800aaf5ff4.
