### ISSUE TITLE
Questions about Partition size and Utilized capacity of memory hierarchy

### ISSUE THREAD

**Issue by ChenpingHU** [NVlabs/timeloop#81]
Hello,

What do Partition size and Utilized capacity mean for certain memory hierarchies in the "timeloop-mapper.stats.txt" file? I found they can be the same and different as well, so I am very confused about it. Thank you!

**Comment by angshuman-parashar** [comment]
Partition size is the total number of unique elements in each tensor that flow through that unit over the course of execution of the entire workload. Utilized capacity is the tile size (of each tensor) that's mapped to each unit.
