### ISSUE TITLE
Question about LinkTransfer

### ISSUE THREAD

**Issue by darrenkao** [NVlabs/timeloop#82]
Hello,

What is the meaning of Link Transfer parameters?
Why my link transfer parameter is always 0 (Despite I let "gEnableLinkTransfers" be true in the code)?

**Comment by angshuman-parashar** [comment]
Whether link transfers happen or not depends on the mapping. There are many mappings where the data sets across neighboring PEs do not overlap over consecutive cycles, in which case there won't be any PE->PE transfers.
