### ISSUE TITLE
Network energy with multiple instances

### ISSUE THREAD

**Issue by MarkHoreni** [NVlabs/timeloop#83]
In line 298 of src/model/network-simple-multicast.cpp the stat accessor calls "stats_.energy.at(pv)" to be saved as the network's energy, but according to line 284-285, this is the energy of an instance of the network, while lines 287-288 shows that the total energy of all instances of this network is "stats_.energy.at(pv) * stats_.utilized_instances.at(pv)".

Looking at line 836 of src/model/buffer.cpp, storage energy of a buffer is "stats_.energy.at(pv) * stats_.utilized_instances.at(pv)." It would make sense to me that the network energy should be inclusive of total instances like the buffer energy is.

I'm not sure if this is intended, but my calculations were different from when I did them by hand, and were fixed when I changed the line in network-simple-multicast.cpp to multiply by number of instances.

**Comment by angshuman-parashar** [comment]
Fixed. Could you please verify vs. your hand calculations?

**Comment by MarkHoreni** [comment]
Looks good! Thanks!
