### ISSUE TITLE
how to write dimension order in problem:

### ISSUE THREAD

**Issue by leehc257** [NVlabs/timeloop#85]
![image](https://user-images.githubusercontent.com/55521614/117907408-bb1d2f00-b311-11eb-8c6c-4b04818ca0c5.png)

i think that dimension order is simple listing of FOR loop statements, but your pdf slide(exercise 6) is not match this loop
how to write dimension order?? 
e.g) FOR loop @ left side  <-> dimensions: @ right side 
              R S P Q C K N        <->         C K R S P Q N(miss match)

**Comment by angshuman-parashar** [comment]
Dimension order is irrelevant in the problem spec. The ranks aren't meant to be ordered. The for loop is human-readable but imposes a specific rank order that we do not want to impose at this stage. It's only when we describe a mapping that we want to impose a rank ordering.

**Comment by leehc257** [comment]
I have a more question.
do you mean dimension order is not affect simulation result ?? 
I have tested simple dimension order changing @ exercise 6(  C M R S N P Q -> M C R S N P Q )
then, energy report stats changed
Is this because of constraints, not dimensional order?

**Comment by angshuman-parashar** [comment]
That action may have perturbed the behavior of the mapper's search heuristic, leading to a different reported optimal mapping within the search parameters. If you use timeloop-model on a deterministic mapping, then the results should be identical regardless of problem shape dimension ordering.

**Comment by leehc257** [comment]
thanks! i understood!
