### ISSUE TITLE
Question about permutation & factors

### ISSUE THREAD

**Issue by leehc257** [NVlabs/timeloop#88]
I've studied exercise 06 (eyeriss arch.),I would like to answer the questions below

1. I know that permutation in constraints expresses the number of cases that a target can have. Is this correct?

2. If the factor is 0, is it correct to change according to the problem spec?
  For example, in the following, it automatically changes to R=3
![image](https://user-images.githubusercontent.com/55521614/118206260-17f92080-b49d-11eb-98fe-78231d8c05d1.png)
![image](https://user-images.githubusercontent.com/55521614/118206287-22b3b580-b49d-11eb-82b8-f14b4f4b2d0d.png)

3. What does the unwritten factor mean?
    In the example above, C is not used, but permutation is included.

**Comment by angshuman-parashar** [comment]
Have you watched the tutorial videos? Most of these questions are addressed there.

**Comment by leehc257** [comment]
I understood while watching the tutorial video again
I corrected my misunderstanding of constraints
Thanks~!
