### ISSUE TITLE
How is the number of utilized instances determined?

### ISSUE THREAD

**Issue by GuillaumeDEVIC** [NVlabs/timeloop#95]
Hello,

In an architecture with several PEs, I observed in the file "timeloop-mapper.stats.txt" that the number of "Utilized instances" is a multiple of the number of MAC operations. This means that the workload is equally distributed on each utilized PEs.

My question is: How is the number of utilized instances determined? Is the number of utilized instances systematically a multiple of the number of MACs?

Thanks in advance

**Comment by Victor-Jung** [comment]
Hi Guillaume,

the number of utilized instances can be found by multiplying the size of spatially assigned loops. 

For example, in [this](https://github.com/NVlabs/timeloop/files/6877005/timeloop-mapper.map.txt) mapping the loops (M, 12) and (S, 11) are spatially unrolled respectively in the X and Y axis of the PE array. If you look into the [stats](https://github.com/NVlabs/timeloop/files/6877038/timeloop-mapper.stats.txt) file you'll notice the utilized instances is 132 (12*11) for level 0 to 3.

Hope this answer will help you.

Best,
Victor
